num_steps: 50000
batch_size: 64
lr: 0.0001
memory_size: 10000
gamma: 0.99
multi_step: 3
target_entropy_ratio: 0.2
start_steps: 500
update_interval: 4
target_update_interval: 100
use_per: False
dueling_net: False
max_episode_steps: 100
log_interval: 5
eval_interval: 5
